all:
  hosts:
    production:
      ansible_host: "{{ lookup('env', 'DEPLOY_HOST') | default(lookup('ansible.builtin.env', 'DEPLOY_HOST')) }}"
      ansible_user: "{{ deploy_user }}"
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3